export const Environment = {

    accessToken : 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjZiMzhlZDktYjA5Ny00MTViLTliZGItNGFkZjE3OTJhZjlhIiwiZW1haWwiOiJzYXJhbmdhZ2FtYWdlMjRAZ21haWwuY29tIiwiZmlyc3ROYW1lIjoiU2FyYW5nYSIsImxhc3ROYW1lIjoiR2FtYWdlIiwicm9sZSI6InN0YWZmIiwiYXZhdGFyIjoiIiwic3RhdHVzIjoiYWN0aXZlIn0sImlhdCI6MTcwMDA0NjM1MSwiZXhwIjoxNzAwMTMyNzUxfQ.bqik8KWLvL_ot0bJ90VE--NJ_6KdmNURPaFVcgL370k',
    apiBaseURL : 'http://localhost:8080/api/v1'

}